[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version = "0.0.1"

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.flakehell]
exclude = ["venv", "README.md"]
extended_default_ignore=[]  # https://github.com/flakehell/flakehell/issues/10#issuecomment-822720074
format = "colored"
max_line_length = 88
show_source = true

[tool.flakehell.plugins]
pycodestyle = ["+*"]

[tool.mypy]
exclude = ["build", "venv"]
